<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="**\*.ncrunchproject" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" Condition="'$(TargetFramework)' == 'netstandard2.0'">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="10.0.6" />
    <PackageReference Include="Polyfill" Version="10.3.0" Condition="'$(TargetFramework)' == 'netstandard2.0'">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="KeyValueResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>KeyValueResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="KeyValueResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>KeyValueResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>