name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        include-prerelease: false
    - name: install-tools
      run: |
        dotnet tool install --global Arbor.Tooler.GlobalTool --version "*-*"
        dotnet tool install --global Arbor.Build.Bootstrapper --version "*-*"
    - name: build
      env:
        Arbor.Build.NuGet.PackageUpload.Server.ApiKey: ${{ secrets.myget }}
        Arbor.Build.NuGet.PackageUpload.Server.Uri: "https://www.myget.org/F/arbor/api/v2/package"
        Arbor.Build.NuGet.PackageUpload.Enabled: "true"
        Arbor.Build.NuGet.PackageUpload.ForceUploadEnabled: "true"
      run: build\build.bat
