name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: install-tools
      env:
        NuGetPassword: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet tool install --global Arbor.Tooler.GlobalTool
        dotnet tool install --global Arbor.Build.Bootstrapper
        dotnet-arbor-tooler -outputdirectory=C:\Tools\NuGet
        C:\Tools\NuGet\nuget.exe source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/niklaslundberg/index.json" -UserName niklaslundberg -Password "%NuGetPassword%"
    - name: build
      env:
        Arbor.X.NuGet.PackageUpload.Server.ApiKey: ${{ secrets.GITHUB_TOKEN }}
        Arbor.X.NuGet.PackageUpload.Server.Uri: "https://nuget.pkg.github.com/niklaslundberg/index.json"
        Arbor.X.NuGet.PackageUpload.Enabled: "true"
        Arbor.X.NuGet.PackageUpload.ForceUploadEnabled: "true"
      run: build\build.bat
