name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: install-tools
      run: dotnet tool install --global Arbor.Tooler.GlobalTool
    - name: build
      run: build\build.bat
