name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    
    steps:
    - uses: actions/checkout@v1
    - name: install-tools
      run: |
        dotnet tool install --global Arbor.Tooler.GlobalTool
        dotnet tool install --global Arbor.Build.Bootstrapper
    - name: build
      env: # Or as an environment variable
        TestPassword1: ${{ secrets.TestPassword }}
      run: build\build.bat
